backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

# publish_mode: editorial_workflow

collections:
  - name: "menu"
    label: "Menu"
    folder: "content/menu"
    create: true
    path: "{{title}}/index"
    media_folder: ""
    public_folder: ""
    fields:
      - label: "Category"
        name: "category"
        widget: "select"
        options:
          - { label: "Breakfast", value: "breakfast" }
          - { label: "Lunch", value: "lunch" }
          - { label: "Snacks", value: "snacks" }
          - { label: "Dinner", value: "dinner" }
      - { label: "Name", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Price", name: "price", widget: "number" }
  - name: "gallery"
    label: "Gallery"
    folder: "content/gallery"
    create: true
    path: "{{title}}/index"
    media_folder: ""
    public_folder: ""
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
